# Generated by Django 4.1.6 on 2023-02-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postcards", "0002_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
