# Generated by Django 4.1.6 on 2023-02-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postcards", "0004_alter_location_country_alpha2"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["country_alpha2", "full_name"]},
        ),
        migrations.RemoveField(
            model_name="location",
            name="country_alpha3",
        ),
        migrations.AlterField(
            model_name="location",
            name="lat",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="location",
            name="lng",
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
