# Generated by Django 4.1.6 on 2023-02-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postcards", "0006_location_type_alter_location_check_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="lat",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="lng",
            new_name="longitude",
        ),
        migrations.AlterField(
            model_name="location",
            name="check_by",
            field=models.CharField(
                choices=[
                    ("2gis", "2GIS"),
                    ("dadata", "DaData"),
                    ("google_api", "Google API"),
                ],
                max_length=128,
                null=True,
            ),
        ),
    ]
