# Generated by Django 4.1.6 on 2023-02-15 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("postcards", "0007_rename_lat_location_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="check_by",
            field=models.CharField(
                choices=[
                    ("2gis", "2GIS"),
                    ("dadata", "DaData"),
                    ("google_api", "Google API"),
                    ("yandex_maps", "Yandex Maps"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="google_place_id",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.CreateModel(
            name="Postcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.DecimalField(decimal_places=3, max_digits=4)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("received", "Received")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("sent_date", models.DateField()),
                ("received_date", models.DateField()),
                (
                    "from_location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="postcards.location",
                    ),
                ),
            ],
            options={
                "ordering": ["sent_date", "received_date"],
            },
        ),
    ]
