# Generated by Django 4.1.6 on 2023-02-15 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("postcards", "0009_postcard_to_location_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="check_by",
            field=models.CharField(
                choices=[
                    ("2gis", "2GIS"),
                    ("dadata", "DaData"),
                    ("google_api", "Google API"),
                    ("google_maps", "Google Maps"),
                    ("yandex_maps", "Yandex Maps"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="distance",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="from_location_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="from_location_id",
                to="postcards.location",
            ),
        ),
        migrations.AlterField(
            model_name="postcard",
            name="status",
            field=models.CharField(
                choices=[("sent", "Sent"), ("received", "Received")],
                default="sent",
                max_length=16,
            ),
            preserve_default=False,
        ),
    ]
