# Generated by Django 4.1.6 on 2023-02-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postcards", "0010_alter_location_check_by_alter_postcard_distance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcard",
            name="received_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
