# Generated by Django 4.1.6 on 2023-02-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postcards", "0011_alter_postcard_received_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcard",
            name="status",
            field=models.CharField(
                choices=[("sent", "Sent"), ("received", "Received")],
                default="sent",
                max_length=16,
            ),
        ),
    ]
